name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup variables
      id: variables
      run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@v3

    - name: Package
      run: zip -r Fusion.zip audio data fonts img mod-appendix

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: Fusion.zip
        name: ${{ steps.variables.outputs.version }}
        generate_release_notes: true
